# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy code and requirements
COPY pokepipeline.py .
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default command
CMD ["python", "pokepipeline.py"]


